spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.106/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
        default-property-inclusion: non_null
server:
  context-path: /sell


wechat:
  mpAppId: wx3336091da1d33f27
  mpAppSecret: b26c4d35e1cfb7d3b38ecbe10ea670de

  mchId: 1483469312
  mchKey: c976503d34ca432c601361f969fd8d85
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://swf.natapp1.cc/sell/pay/notify





